export const STORAGE_KEYS = {
  // Auth
  TOKEN: "rdg_token",
  USER: "rdg_user",
  ADMIN_TOKEN: "rdg_admin_token",
  ADMIN_USER: "rdg_admin_user",

  // Password reset
  RESET_EMAIL: "rdg_reset_email",
  RESET_TOKEN: "rdg_reset_token",

  // Onboarding steps (session storage)
  ONBOARDING_STEP1: "rdg_onboarding_step1",
  ONBOARDING_STEP2: "rdg_onboarding_step2",
  ONBOARDING_STEP3: "rdg_onboarding_step3",
  ONBOARDING_STEP4: "rdg_onboarding_step4",

  // Misc
  ONBOARDING_COOKIE: "rdg_onboarding",
} as const;

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" }
];

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  OTP_VERIFICATION: "/otp-verification",
  CREATE_PASSWORD: "/create-password",
  ONBOARDING: "/onboarding",

  DASHBOARD: "/dashboard",
  FUNDERS: "/funders",
  MATCHES: "/matches",
  APPLICATIONS: "/applications",
  TRACKER: "/tracker",
  OUTREACH: "/outreach",
  FOLLOWUPS: "/follow-ups",
  WINS: "/wins",
  ALERTS: "/alerts",
  SETTINGS: "/settings",

  ADMIN: "/admin",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_AGENCIES: "/admin/agencies",
  ADMIN_FUNDERS: "/admin/funders",
  ADMIN_APPLICATIONS: "/admin/applications",
  ADMIN_OPPORTUNITIES: "/admin/opportunities",
  ADMIN_MATCHES: "/admin/matches",
  ADMIN_USERS: "/admin/users",
  ADMIN_SETTINGS: "/admin/settings",
} as const;
