const Digest = require('./digest.schema');
const Match = require('../matches/match.schema');
const Organization = require('../organizations/organization.schema');
const outboxService = require('../outbox/outbox.service');
const openai = require('../../config/openai.config');
const { AppError } = require('../../middlewares/error.middleware');
const logger = require('../../utils/logger');

const getAll = async ({ page = 1, limit = 20, status, organizationId }) => {
  const query = {};
  if (status) query.status = status;
  if (organizationId) query.organization = organizationId;

  return Digest.paginate(query, {
    page: parseInt(page),
    limit: parseInt(limit),
    sort: { createdAt: -1 },
    populate: [
      { path: 'organization', select: 'name email' },
      { path: 'user', select: 'firstName lastName email' },
    ],
  });
};

const getOne = async (id) => {
  const digest = await Digest.findById(id)
    .populate('organization')
    .populate('user', 'firstName lastName email')
    .populate({ path: 'matches', populate: { path: 'opportunity', select: 'title funder maxAmount deadline sourceUrl status' } });
  if (!digest) throw new AppError('Digest not found', 404);
  return digest;
};

const buildHtml = (org, matches, aiIntro) => {
  const rows = matches
    .slice(0, 12)
    .map((m) => {
      const opp = m.opportunity;
      const deadlineText = opp.deadline ? new Date(opp.deadline).toLocaleDateString() : 'No deadline';
      const amountText = opp.maxAmount ? `$${opp.maxAmount.toLocaleString()}` : 'N/A';
      return `
        <div style="margin-bottom:24px;padding:20px;border:1px solid #e0e0e0;border-radius:8px;">
          <h3 style="margin:0 0 8px;color:#ef3e34;">${opp.title || 'Untitled'}</h3>
          <p style="margin:4px 0;"><strong>Funder:</strong> ${opp.funder || 'Unknown'}</p>
          <p style="margin:4px 0;"><strong>Fit Score:</strong> ${m.fitScore}/100</p>
          <p style="margin:4px 0;"><strong>Max Award:</strong> ${amountText}</p>
          <p style="margin:4px 0;"><strong>Deadline:</strong> ${deadlineText}</p>
          <p style="margin:4px 0;"><strong>Recommendation:</strong> ${m.recommendedAction || ''}</p>
          ${opp.sourceUrl ? `<p style="margin:8px 0;"><a href="${opp.sourceUrl}" style="color:#ef3e34;">View Opportunity →</a></p>` : ''}
        </div>`;
    })
    .join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;padding:24px;">
      <h1 style="color:#0d0d0d;border-bottom:3px solid #ef3e34;padding-bottom:12px;">
        Red Dog Radio Grant Intelligence — Weekly Digest
      </h1>
      <h2 style="color:#444;">${org.name}</h2>
      <p style="color:#666;line-height:1.6;">${aiIntro}</p>
      <h3 style="color:#0d0d0d;margin-top:32px;">TOP OPPORTUNITIES THIS WEEK</h3>
      ${rows}
      <hr style="border:none;border-top:1px solid #eee;margin:32px 0;" />
      <p style="color:#999;font-size:12px;text-align:center;">
        Generated by Red Dog Radio Grant Intelligence Platform
      </p>
    </div>`;
};

const generateAiIntro = async (orgName, count) => {
  const defaultIntro = `This week's digest includes ${count} grant opportunities selected for ${orgName}. Each has been scored for fit based on your organization's profile. We recommend reviewing all opportunities promptly, as deadlines can be competitive.`;

  if (!openai) {
    logger.info('[STUB] OpenAI not configured — using default digest intro');
    return defaultIntro;
  }

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'user',
          content: `Write a short professional 2-4 sentence intro for a weekly funding digest email for ${orgName}. The digest includes ${count} grant opportunities. Mention the value of reviewing them promptly. Plain text only.`,
        },
      ],
      max_tokens: 200,
    });
    return response.choices[0]?.message?.content?.trim() || defaultIntro;
  } catch (err) {
    logger.warn('OpenAI digest intro failed, using default:', err.message);
    return defaultIntro;
  }
};

const generateDigest = async (organizationId, userId, weekStart, weekEnd, saveToDb = true) => {
  const org = await Organization.findById(organizationId);
  if (!org) throw new AppError('Organization not found', 404);

  const matches = await Match.find({
    organization: organizationId,
    fitScore: { $gte: 55 },
  })
    .populate({ path: 'opportunity', match: { status: { $in: ['open', 'closing'] } } })
    .sort({ fitScore: -1 });

  const validMatches = matches.filter((m) => m.opportunity);

  const aiIntro = await generateAiIntro(org.name, validMatches.length);
  const html = buildHtml(org, validMatches, aiIntro);
  const subject = `Grant Intelligence Weekly Digest — ${org.name}`;

  if (!saveToDb) {
    return { subject, html, itemCount: validMatches.length, aiIntro };
  }

  const digest = await Digest.create({
    organization: organizationId,
    user: userId,
    weekStart,
    weekEnd,
    matches: validMatches.map((m) => m._id),
    aiIntro,
    status: 'draft',
    itemCount: validMatches.length,
  });

  return digest;
};

const sendDigest = async (digestId, recipientEmail, recipientName) => {
  const digest = await getOne(digestId);
  const org = digest.organization;

  const html = buildHtml(org, digest.matches, digest.aiIntro);
  const subject = `Grant Intelligence Weekly Digest — ${org.name}`;

  await outboxService.queueEmail({
    recipient: recipientEmail,
    recipientName,
    subject,
    htmlBody: html,
    emailType: 'weekly_digest',
    relatedOrganization: org._id,
  });

  digest.status = 'sent';
  digest.sentAt = new Date();
  await digest.save();

  return digest;
};

module.exports = { getAll, getOne, generateDigest, sendDigest };
